/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.*;


import com.google.zxing.*;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;

import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.videoio.VideoCapture;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.util.Timer;
import java.util.TimerTask;


/**
 *
 * @author jeson
 */
public class home extends javax.swing.JFrame {
    
    private Timer cameraTimer;
    private VideoCapture videoCapture;
    private int currentCameraIndex = 0;
    private boolean scanning = true;
    

    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        navbarpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dashboardbutton = new javax.swing.JButton();
        eventsbutton = new javax.swing.JButton();
        accountsbutton = new javax.swing.JButton();
        attendancebutton = new javax.swing.JButton();
        scanqrbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        dashboardpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        eventspanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        accountspanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        attendancepanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        scanqrpanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        change_cam = new javax.swing.JComboBox<>();
        camera = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("home");
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanel2.setLayout(new java.awt.BorderLayout());

        navbarpanel.setBackground(new java.awt.Color(25, 42, 86));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ACLC");
        jLabel6.setAlignmentX(0.2F);

        dashboardbutton.setBackground(new java.awt.Color(25, 42, 86));
        dashboardbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dashboardbutton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardbutton.setText("Dashboard");
        dashboardbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardbuttonActionPerformed(evt);
            }
        });

        eventsbutton.setBackground(new java.awt.Color(25, 42, 86));
        eventsbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eventsbutton.setForeground(new java.awt.Color(255, 255, 255));
        eventsbutton.setText("Events");
        eventsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsbuttonActionPerformed(evt);
            }
        });

        accountsbutton.setBackground(new java.awt.Color(25, 42, 86));
        accountsbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        accountsbutton.setForeground(new java.awt.Color(255, 255, 255));
        accountsbutton.setText("Accounts");
        accountsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsbuttonActionPerformed(evt);
            }
        });

        attendancebutton.setBackground(new java.awt.Color(25, 42, 86));
        attendancebutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        attendancebutton.setForeground(new java.awt.Color(255, 255, 255));
        attendancebutton.setText("Attendance");
        attendancebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendancebuttonActionPerformed(evt);
            }
        });

        scanqrbutton.setBackground(new java.awt.Color(25, 42, 86));
        scanqrbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        scanqrbutton.setForeground(new java.awt.Color(255, 255, 255));
        scanqrbutton.setText("Scan QR");
        scanqrbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanqrbuttonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EDUHOUSE EVENTS");

        javax.swing.GroupLayout navbarpanelLayout = new javax.swing.GroupLayout(navbarpanel);
        navbarpanel.setLayout(navbarpanelLayout);
        navbarpanelLayout.setHorizontalGroup(
            navbarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navbarpanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dashboardbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendancebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scanqrbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(navbarpanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarpanelLayout.setVerticalGroup(
            navbarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(dashboardbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eventsbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountsbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attendancebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scanqrbutton)
                .addContainerGap())
        );

        jPanel2.add(navbarpanel, java.awt.BorderLayout.WEST);

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout dashboardpanelLayout = new javax.swing.GroupLayout(dashboardpanel);
        dashboardpanel.setLayout(dashboardpanelLayout);
        dashboardpanelLayout.setHorizontalGroup(
            dashboardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardpanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dashboardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        dashboardpanelLayout.setVerticalGroup(
            dashboardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        mainpanel.add(dashboardpanel, "card6");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Events");

        javax.swing.GroupLayout eventspanelLayout = new javax.swing.GroupLayout(eventspanel);
        eventspanel.setLayout(eventspanelLayout);
        eventspanelLayout.setHorizontalGroup(
            eventspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventspanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(eventspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        eventspanelLayout.setVerticalGroup(
            eventspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        mainpanel.add(eventspanel, "card5");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Accounts");

        javax.swing.GroupLayout accountspanelLayout = new javax.swing.GroupLayout(accountspanel);
        accountspanel.setLayout(accountspanelLayout);
        accountspanelLayout.setHorizontalGroup(
            accountspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountspanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(accountspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        accountspanelLayout.setVerticalGroup(
            accountspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        mainpanel.add(accountspanel, "card4");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Attendance");

        javax.swing.GroupLayout attendancepanelLayout = new javax.swing.GroupLayout(attendancepanel);
        attendancepanel.setLayout(attendancepanelLayout);
        attendancepanelLayout.setHorizontalGroup(
            attendancepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendancepanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(attendancepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        attendancepanelLayout.setVerticalGroup(
            attendancepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendancepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        mainpanel.add(attendancepanel, "card3");

        jPanel3.setBackground(new java.awt.Color(0, 3, 81));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("QR Scanner");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select Camera:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(change_cam, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(camera, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(change_cam, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(camera, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout scanqrpanelLayout = new javax.swing.GroupLayout(scanqrpanel);
        scanqrpanel.setLayout(scanqrpanelLayout);
        scanqrpanelLayout.setHorizontalGroup(
            scanqrpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scanqrpanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        scanqrpanelLayout.setVerticalGroup(
            scanqrpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainpanel.add(scanqrpanel, "card2");

        jPanel2.add(mainpanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eventsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsbuttonActionPerformed
        // TODO add your handling code here:                                            
            CardLayout cl = (CardLayout) mainpanel.getLayout();
            cl.show(mainpanel, "card5");
               stopCamera();
    }//GEN-LAST:event_eventsbuttonActionPerformed

    private void dashboardbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardbuttonActionPerformed
        // TODO add your handling code here:                                             
            CardLayout cl = (CardLayout) mainpanel.getLayout();
            cl.show(mainpanel, "card6");
               stopCamera();
    }//GEN-LAST:event_dashboardbuttonActionPerformed

    private void attendancebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendancebuttonActionPerformed
        // TODO add your handling code here:                                             
            CardLayout cl = (CardLayout) mainpanel.getLayout();
            cl.show(mainpanel, "card3");  
               stopCamera();
    }//GEN-LAST:event_attendancebuttonActionPerformed

    private void scanqrbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanqrbuttonActionPerformed
        // TODO add your handling code here:                                  
            CardLayout cl = (CardLayout) mainpanel.getLayout();
            cl.show(mainpanel, "card2");
            initCameraSystem();
    }//GEN-LAST:event_scanqrbuttonActionPerformed

    private void accountsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsbuttonActionPerformed
        // TODO add your handling code here:                                              
            CardLayout cl = (CardLayout) mainpanel.getLayout();
            cl.show(mainpanel, "card4");
            stopCamera();
    }//GEN-LAST:event_accountsbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    
    
    
     private void initCameraSystem() {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        listAvailableCameras();
        startCamera(currentCameraIndex);

        change_cam.addActionListener(e -> {
            stopCamera();
            currentCameraIndex = change_cam.getSelectedIndex();
            startCamera(currentCameraIndex);
        });
    }

    private void listAvailableCameras() {
        change_cam.removeAllItems();
        for (int i = 0; i < 5; i++) {
            VideoCapture testCam = new VideoCapture(i);
            if (testCam.isOpened()) {
                change_cam.addItem("Camera " + i);
                testCam.release();
            }
        }
        if (change_cam.getItemCount() == 0) {
            change_cam.addItem("No Camera Found");
        }
    }

    private void startCamera(int cameraIndex) {
        videoCapture = new VideoCapture(cameraIndex);
        if (!videoCapture.isOpened()) {
            System.out.println("Cannot open camera " + cameraIndex);
            return;
        }

        cameraTimer = new Timer();
        cameraTimer.schedule(new TimerTask() {
            @Override
            public void run() {
                if (!scanning) return;

                Mat frame = new Mat();
                if (videoCapture.read(frame)) {
                    BufferedImage bufferedImage = matToBufferedImage(frame);
                    camera.setIcon(new ImageIcon(bufferedImage.getScaledInstance(camera.getWidth(), camera.getHeight(), Image.SCALE_SMOOTH)));  
                    readQRCode(bufferedImage);
                }
            }
        }, 0, 10); 
    }

    private void stopCamera() {
        if (cameraTimer != null) cameraTimer.cancel();
        if (videoCapture != null && videoCapture.isOpened()) {
            videoCapture.release();
        }
    }

    private BufferedImage matToBufferedImage(Mat mat) {
        int type = BufferedImage.TYPE_BYTE_GRAY;
        if (mat.channels() > 1) {
            type = BufferedImage.TYPE_3BYTE_BGR;
        }
        BufferedImage image = new BufferedImage(mat.width(), mat.height(), type);
        final byte[] targetPixels = ((DataBufferByte) image.getRaster().getDataBuffer()).getData();
        mat.get(0, 0, targetPixels);
        return image;
    }

    private void readQRCode(BufferedImage image) {
    try {
        LuminanceSource source = new BufferedImageLuminanceSource(image);
        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
        Result result = new MultiFormatReader().decode(bitmap);

        if (result != null) {
            String qrText = result.getText();
            System.out.println("QR Code detected: " + qrText);
            scanning = false;

            boolean found = checkQRCodeInDatabase(qrText);

            SwingUtilities.invokeLater(() -> {
                if (found) {
                    JOptionPane pane = new JOptionPane("✅ QR Code recognized: " + qrText, JOptionPane.INFORMATION_MESSAGE);
                    JDialog dialog = pane.createDialog(this, "Success");
                    dialog.setModal(false);
                    dialog.setVisible(true);

                    // Auto-close after 2 seconds
                    new Timer().schedule(new java.util.TimerTask() {
                        public void run() {
                            dialog.setVisible(false);
                            scanning = true;
                        }
                    }, 2000);
                } else {
                    JOptionPane.showMessageDialog(this, "❌ QR Code not found in the database.", "Error", JOptionPane.ERROR_MESSAGE);
                    scanning = true;
                }
            });
        }
    } catch (NotFoundException e) {
        // No QR found – ignore
    } catch (Exception e) {
        e.printStackTrace();
    }
}
   
    private boolean checkQRCodeInDatabase(String qrText) {
    boolean exists = false;
    String url = "jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=CONVERT_TO_NULL"; // Change this
    String user = "root";                            // Change this
    String password = "";                        // Change this

    try (Connection conn = DriverManager.getConnection(url, user, password)) {
        String sql = "SELECT * FROM qr_data WHERE qr_id = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, qrText);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            exists = true;
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    return exists;
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountsbutton;
    private javax.swing.JPanel accountspanel;
    private javax.swing.JButton attendancebutton;
    private javax.swing.JPanel attendancepanel;
    private javax.swing.JLabel camera;
    private javax.swing.JComboBox<String> change_cam;
    private javax.swing.JButton dashboardbutton;
    private javax.swing.JPanel dashboardpanel;
    private javax.swing.JButton eventsbutton;
    private javax.swing.JPanel eventspanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel navbarpanel;
    private javax.swing.JButton scanqrbutton;
    private javax.swing.JPanel scanqrpanel;
    // End of variables declaration//GEN-END:variables
}
